"""init

Revision ID: 1f9b4d01d1dd
Revises: 
Create Date: 2022-12-23 20:41:06.159381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9b4d01d1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('league', sa.Enum('English Premier League', 'English Football League Championship', 'Spanish La Liga', 'Italian Serie A', 'Genman Bundesliga', 'French Ligue 1', 'Portuguese Primeira Liga', 'Korean K-league classic', name='league'), nullable=True),
    sa.Column('stadium', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Enum('10,000~20,000', '20~000~30,000', '30,000~40,000', '40,000~50,000', '50,000~60,000', '60,000~70,000', '70,000~80,000', '80,000~90,000', 'over 100,000', name='capacity'), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('manager', sa.String(length=20), nullable=True),
    sa.Column('founded', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.Numeric(precision=15), nullable=True),
    sa.Column('emblem', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nationality', sa.String(length=15), nullable=False),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('position', sa.Enum('Goalkeeper', 'Left-back', 'Left-wingback', 'Centre-back', 'Right-back', 'Right-wingback', 'Defensive-midfilder', 'centre-midfilder', 'Left-midfilder', 'Attacking-midfilder', 'Right-midfilder', 'Forward', name='positiontype'), nullable=False),
    sa.Column('foot', sa.String(), nullable=False),
    sa.Column('club', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_player_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player'))
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_nationality'), ['nationality'], unique=False)

    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.String(length=50), nullable=True),
    sa.Column('bid_amount', sa.Float(precision=20), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_bid_player_id_player')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bid_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_nationality'))

    op.drop_table('player')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    # ### end Alembic commands ###
