"""string

Revision ID: 54eafbfa20b0
Revises: 1f9b4d01d1dd
Create Date: 2022-12-23 21:55:05.629703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54eafbfa20b0'
down_revision = '1f9b4d01d1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.alter_column('bid_amount',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.alter_column('bid_amount',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
